<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Azka_Transaction_Processing_System.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Modules\Customers\" />
    <Folder Include="Modules\Branches\" />
    <Folder Include="Modules\PaymentMethods\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Azka Transaction Processing System.Domain\Azka Transaction Processing System.Domain.csproj" />
  </ItemGroup>

</Project>
